version: '3'

services:
  db-migrator:
    image: caueguedes/qconcurso:prod
    command: [ "./wait-for", "--timeout=3000", "database:5432", "--",
      "bin/rails", "db:migrate" ]
    env_file:
     - .env/production/database
     - .env/production/web
    deploy:
      restart_policy:
        condition: none

  web:
    image: caueguedes/qconcurso:prod
    ports:
      - "80:3000"
    env_file:
      - .env/production/database
      - .env/production/web

  database:
    image: postgres
    env_file:
      - .env/production/database
    volumes:
    - postgres:/var/lib/postgresql/data

  redis:
    image: redis
    env_file:
      - .env/development/redis

volumes:
  gem_cache:
  postgres: