version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    env_file:
      - .env/development/database
      - .env/development/web
      - .env/development/redis
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpack_dev_server
    tty: true
    stdin_open: true

  webpack_dev_server:
    build: .
    command: ./bin/webpack-dev-server
    ports:
      - 3035:3035
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    env_file:
      - .env/development/web
      - .env/development/database
      - .env/development/redis
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

  database:
    image: postgres
    env_file:
      - .env/development/database
    ports:
      - "5432:5432"

  db-migrator:
    build: .
    command: [ "./wait-for", "--timeout=3000", "database:5432", "--",
               "bin/rails", "db:migrate" ]
    volumes:
      - .:/usr/src/app
    env_file:
      - .env/development/database
      - .env/development/web

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env/development/pgadmin
    ports:
      - "8080:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    links:
      - "database:pgsql"

  redis:
    image: redis
    env_file:
      - .env/development/redis

volumes:
  gem_cache:
  pgadmin:
